import { Member } from '@/types/member';

export const mockMembers: Member[] = [
  {
    id: '1', nickname: 'MoonChild_Lima', age: 24, district: 'Miraflores', country: 'Perú',
    bias: 'RM', biasWrecker: 'V', favoriteAlbum: 'Map of the Soul: 7', favoriteSong: 'Moonchild',
    armySince: '2017', arrivalMode: 'sola/o', arrivalTime: '04:00', earlyQueueInterest: true,
    confirmsOctober7: true, confirmsZonaCampoC: true, hasConfirmedTicket: true, acceptedSafetyRules: true,
    instagram: '@moonchild_lima', message: '¡Nos vemos en Campo C! Llevemos luces moradas 💜',
    status: 'approved', createdAt: '2025-08-01T10:00:00Z',
  },
  {
    id: '2', nickname: 'EternalJin', age: 28, district: 'San Isidro', country: 'Perú',
    bias: 'Jin', biasWrecker: 'Jungkook', favoriteAlbum: 'Love Yourself: Answer', favoriteSong: 'Epiphany',
    armySince: '2018', arrivalMode: 'acompañada/o', arrivalTime: '08:00', earlyQueueInterest: false,
    confirmsOctober7: true, confirmsZonaCampoC: true, hasConfirmedTicket: true, acceptedSafetyRules: true,
    message: 'Es mi primer concierto de BTS, estoy tan emocionada 🥹',
    status: 'approved', createdAt: '2025-08-02T14:30:00Z',
  },
  {
    id: '3', nickname: 'SugaRush_PE', age: 22, district: 'Surco', country: 'Perú',
    bias: 'Suga', favoriteAlbum: 'Wings', favoriteSong: 'First Love',
    armySince: '2016', arrivalMode: 'sola/o', arrivalTime: '05:00', earlyQueueInterest: true,
    confirmsOctober7: true, confirmsZonaCampoC: true, hasConfirmedTicket: true, acceptedSafetyRules: true,
    instagram: '@sugarush_pe', message: 'Yoongi es mi inspiración. Nos cuidamos entre todas 💜',
    status: 'approved', createdAt: '2025-08-03T09:15:00Z',
  },
  {
    id: '4', nickname: 'HobiSunshine', age: 20, district: 'Lince', country: 'Perú',
    bias: 'J-Hope', biasWrecker: 'Jimin', favoriteAlbum: 'Love Yourself: Her', favoriteSong: 'Trivia: Just Dance',
    armySince: '2019', arrivalMode: 'acompañada/o', arrivalTime: '10:00', earlyQueueInterest: false,
    confirmsOctober7: true, confirmsZonaCampoC: true, hasConfirmedTicket: true, acceptedSafetyRules: true,
    message: 'Voy con mi hermana, hagamos grupo de cola 🌞',
    status: 'approved', createdAt: '2025-08-04T16:00:00Z',
  },
  {
    id: '5', nickname: 'ChimChim_Arequipa', age: 26, district: 'Arequipa', country: 'Perú',
    bias: 'Jimin', biasWrecker: 'V', favoriteAlbum: 'Map of the Soul: Persona', favoriteSong: 'Filter',
    armySince: '2020', arrivalMode: 'sola/o', arrivalTime: '03:00', earlyQueueInterest: true,
    confirmsOctober7: true, confirmsZonaCampoC: true, hasConfirmedTicket: true, acceptedSafetyRules: true,
    instagram: '@chimchim_aqp', message: 'Viajo desde Arequipa, busco grupo para hacer cola juntas',
    status: 'approved', createdAt: '2025-08-05T11:30:00Z',
  },
  {
    id: '6', nickname: 'TaeTae_Purple', age: 23, district: 'Barranco', country: 'Perú',
    bias: 'V', biasWrecker: 'Jungkook', favoriteAlbum: 'BE', favoriteSong: 'Sweet Night',
    armySince: '2019', arrivalMode: 'sola/o', arrivalTime: '06:00', earlyQueueInterest: true,
    confirmsOctober7: true, confirmsZonaCampoC: true, hasConfirmedTicket: true, acceptedSafetyRules: true,
    message: 'Borahae desde Barranco 💜 cuidémonos entre ARMYs',
    status: 'approved', createdAt: '2025-08-06T08:45:00Z',
  },
  {
    id: '7', nickname: 'GoldenJK_Peru', age: 21, district: 'San Borja', country: 'Perú',
    bias: 'Jungkook', biasWrecker: 'RM', favoriteAlbum: 'Proof', favoriteSong: 'Euphoria',
    armySince: '2018', arrivalMode: 'acompañada/o', arrivalTime: '07:00', earlyQueueInterest: false,
    confirmsOctober7: true, confirmsZonaCampoC: true, hasConfirmedTicket: true, acceptedSafetyRules: true,
    instagram: '@goldenjk_pe', message: 'Jungkook es mi universo. Nos vemos el 7 de octubre!',
    status: 'approved', createdAt: '2025-08-07T13:20:00Z',
  },
  {
    id: '8', nickname: 'BangtanForever', age: 25, district: 'Callao', country: 'Perú',
    bias: 'Suga', biasWrecker: 'Jin', favoriteAlbum: 'The Most Beautiful Moment in Life Pt.2', favoriteSong: 'Run',
    armySince: '2015', arrivalMode: 'sola/o', arrivalTime: '04:30', earlyQueueInterest: true,
    confirmsOctober7: true, confirmsZonaCampoC: true, hasConfirmedTicket: true, acceptedSafetyRules: true,
    message: 'ARMY desde 2015, esta es la noche que esperé toda mi vida',
    status: 'approved', createdAt: '2025-08-08T10:00:00Z',
  },
  {
    id: '9', nickname: 'PurpleDream_Cusco', age: 19, district: 'Cusco', country: 'Perú',
    bias: 'Jimin', biasWrecker: 'J-Hope', favoriteAlbum: 'Love Yourself: Tear', favoriteSong: 'Fake Love',
    armySince: '2021', arrivalMode: 'sola/o', arrivalTime: '05:30', earlyQueueInterest: true,
    confirmsOctober7: true, confirmsZonaCampoC: true, hasConfirmedTicket: true, acceptedSafetyRules: true,
    message: 'Viajo sola desde Cusco, ojalá encontrar grupo 💜',
    status: 'approved', createdAt: '2025-08-09T15:10:00Z',
  },
  {
    id: '10', nickname: 'RM_Filosofia', age: 27, district: 'Jesús María', country: 'Perú',
    bias: 'RM', favoriteAlbum: 'Map of the Soul: 7', favoriteSong: 'Persona',
    armySince: '2016', arrivalMode: 'acompañada/o', arrivalTime: '09:00', earlyQueueInterest: false,
    confirmsOctober7: true, confirmsZonaCampoC: true, hasConfirmedTicket: true, acceptedSafetyRules: true,
    message: 'Namjoon me enseñó a amarme. Nos vemos Campo C.',
    status: 'approved', createdAt: '2025-08-10T12:00:00Z',
  },
  {
    id: '11', nickname: 'ButterARMY', age: 22, district: 'La Molina', country: 'Perú',
    bias: 'V', biasWrecker: 'Jimin', favoriteAlbum: 'Young Forever', favoriteSong: 'Spring Day',
    armySince: '2020', arrivalMode: 'sola/o', arrivalTime: '06:30', earlyQueueInterest: true,
    confirmsOctober7: true, confirmsZonaCampoC: true, hasConfirmedTicket: true, acceptedSafetyRules: true,
    instagram: '@butterarmy_pe', message: 'Spring Day me hace llorar siempre. Campo C será mágico.',
    status: 'approved', createdAt: '2025-08-11T17:30:00Z',
  },
  {
    id: '12', nickname: 'DynamiteGirl', age: 30, district: 'Magdalena', country: 'Perú',
    bias: 'J-Hope', biasWrecker: 'Suga', favoriteAlbum: 'Dark & Wild', favoriteSong: 'Danger',
    armySince: '2014', arrivalMode: 'acompañada/o', arrivalTime: '11:00', earlyQueueInterest: false,
    confirmsOctober7: true, confirmsZonaCampoC: true, hasConfirmedTicket: true, acceptedSafetyRules: true,
    message: 'ARMY desde el inicio. Nos cuidamos, nos apoyamos. Borahae 💜',
    status: 'approved', createdAt: '2025-08-12T09:45:00Z',
  },
  {
    id: '13', nickname: 'PendingARMY', age: 23, district: 'Pueblo Libre', country: 'Perú',
    bias: 'Jungkook', favoriteAlbum: 'Proof', favoriteSong: 'Yet To Come',
    armySince: '2022', arrivalMode: 'sola/o', arrivalTime: '07:00', earlyQueueInterest: false,
    confirmsOctober7: true, confirmsZonaCampoC: true, hasConfirmedTicket: true, acceptedSafetyRules: true,
    message: 'Esperando verificación',
    status: 'pending', createdAt: '2025-08-13T10:00:00Z',
  },
];
