// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wlnkvanekfiqxbfvaluc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indsbmt2YW5la2ZpcXhiZnZhbHVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU3ODIyODAsImV4cCI6MjA5MTM1ODI4MH0.fVY1jlB4PSdHafHSN-J3oADXpuKp6ql_LSTIL5zlzCA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});